### ISSUE TITLE
Library not loaded: @rpath/FavIcon.framework/FavIcon: "Image not found"

### ISSUE THREAD

**Issue by ghost** [leonbreedt/FavIcon#11]
I downloaded this project, build it and dragged the framework across to my project. Then I am trying to build it, and I am getting:

`dyld: Library not loaded: @rpath/FavIcon.framework/FavIcon
  Referenced from: /Users/username/Library/Developer/CoreSimulator/Devices/....
  Reason: image not found
(lldb) `

**Comment by leonbreedt** [comment]
@warhost, does it work if you add the framework to *Embedded Binaries* section of your app target?

**Comment by leonbreedt** [comment]
Library has been rewritten from scratch, and is now also available via CocoaPods which would ensure the appropriate settings are set so that this error does not happen. Closing.
