### ISSUE TITLE
How to use and import in SWIFT4?

### ISSUE THREAD

**Issue by gaborcsontos** [leonbreedt/FavIcon#12]
I tried to add into my project, but to be honest, I ended up with a bunch of errors, and also it doesn't find these files.
#import "libxml/tree.h"
#import "libxml/xpath.h"
#import "libxml/xpathInternals.h"

**Comment by leonbreedt** [comment]
Hi! Thanks for the report.

Yes, this library needs some Swift 4 love!

Hopefully I will get some time to look at the forks and see if someone has done something useful.

Cheers!

**Comment by vikmarino** [comment]
Spent 2h+ trying to make it work with swift 4 but due to my lack of exp. in iOS, I couldn't. 
Please, make it to CocoaPods. 

Thanks @leonbreedt !

**Comment by leonbreedt** [comment]
Just an update @csontosgabor and @vitovalov - Busy rewriting the library for Swift 4.

Will make it a CocoaPod as well, which should fix the libxml path issues for you.

**Comment by gaborcsontos** [comment]
@leonbreedt Thanks mate. Hope it will be ready soon. By the way incredible job so far as well.!:)
Peace, love from London.

**Comment by leonbreedt** [comment]
@gabormajorszki @vitovalov I've released the rewritten Swift 4.0 version of this library, it's now on CocoaPods.org as well, see the README for the snippet you need to put in your `Podfile`.

Released version is `3.0.1`.

**Comment by vitovalov** [comment]
Not sure, but I just added it as usually did with other pods, and got this message after doing `pod install`:
`[!] Unable to find a specification for FavIcon`

**Comment by gaborcsontos** [comment]
Cheers mate!!! ::) God bless you!
