### ISSUE TITLE
Missing required module 'libxmlFavicon'

### ISSUE THREAD

**Issue by suzuhiroruri** [leonbreedt/FavIcon#16]
As swift4, when I import FavIcon, there's message that "Missing required module 'libxmlFavicon'"

**Comment by leonbreedt** [comment]
@suzuhiroruri are you using CocoaPods, or Carthage? also, please confirm if you have command-line tools for Xcode installed

https://developer.apple.com/download/more/

FavIcon expects libxml2 headers to be in `/usr/include/libxml2`, if you installed App Store Xcode without installing Command-Line Tools then it may be missing.

**Comment by leonbreedt** [comment]
Closing as can't reproduce with newer builds.
