### ISSUE TITLE
Cannot load module FavIcon as Favicon

### ISSUE THREAD

**Issue by tommycarpi** [leonbreedt/FavIcon#18]
Xcode v9.4.1
Swift v4.1

I get the following error upon 
`import FavIcon`

**Cannot load module "FavIcon" as "Favicon"**

Installed with Cocoapods v1.5.3

**Comment by leonbreedt** [comment]
Argh, I'm sure its because Apple moved libxml2 again. Thanks for the report, I'll look into it.

**Comment by leonbreedt** [comment]
@tommycarpi I just tried it on Xcode 9.4.1 on High Sierra.

```shell
$ swift --version
Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
$ cat /Applications/Xcode.app/Contents/Info.plist | plutil -convert xml1 -o - - | grep -A 1 CFBundleShortVersionString
        <key>CFBundleShortVersionString</key>
        <string>9.4.1</string>
```

And it worked. Attached is the project workspace.
[FavIconConsumer.zip](https://github.com/leonbreedt/FavIcon/files/2213246/FavIconConsumer.zip)

Can you confirm if you have Xcode command-line tools installed? If not, run `xcode-select --install`.

**Comment by leonbreedt** [comment]
Can't reproduce with CLT installed.
