### ISSUE TITLE
libxml/xmlversion.h not found

### ISSUE THREAD

**Issue by waltcow** [leonbreedt/FavIcon#21]
Hi,  I am using Carthage to include this lib to my project

 when I import FavIcon,  there's message show below
```
include/libxml2/libxml/HTMLparser.h:15:10: 'libxml/xmlversion.h' file not found
```

**Comment by waltcow** [comment]
I solved it by add  `$SDKROOT/usr/include/libxml2` in `Header search paths` in Build settings

**Comment by leonbreedt** [comment]
@waltcow Yeah, I've had no end of problems with the location of libxml2 moving around between Xcode releases. The sources currently depend on it being in `/usr/include/libxml2`, which is installed when you install command-line tools. Hopefully SDKROOT approach will work with the `.podspec` too. Thanks for letting me know.

**Comment by iwasrobbed-ks** [comment]
Would it make sense to update this in https://github.com/leonbreedt/FavIcon/blob/master/FavIcon.podspec#L29? 

We see this as well:

>/Applications/Xcode-10.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/usr/include/libxml2/libxml/HTMLparser.h:15:10: 'libxml/xmlversion.h' file not found
