### ISSUE TITLE
Runtime Search Path for FavIcon-macOS target

### ISSUE THREAD

**Issue by gk-plastics** [leonbreedt/FavIcon#22]
Thanks for the wonderful library. We used FavIcon one of our macOS app and it is working awesome.

Recently we encountered an issue where our app crashes immediately after launch only when an older version of Xcode is installed in the Applications directory on user's Mac. (It works fine when no Xcode has been installed.)

<details>
<summary>Crash report</summary>

	Process:               Haste [899]
	Path:                  /Applications/Haste.app/Contents/MacOS/Haste
	Identifier:            com.plastic-software.Haste
	Version:               ???
	App Item ID:           1175250324
	App External ID:       828388155
	Code Type:             X86-64 (Native)
	Parent Process:        ??? [1]
	Responsible:           Haste [899]
	User ID:               501

	Date/Time:             2018-09-06 16:40:06.070 +0900
	OS Version:            Mac OS X 10.11.6 (15G22010)
	Report Version:        11
	Anonymous UUID:        FF5EE1F3-AFED-30DE-A52F-3C2C7A1FDD6A

	Sleep/Wake UUID:       2DB636DE-3D66-49FB-B0C3-AAAED33AC960

	Time Awake Since Boot: 2100 seconds
	Time Since Wake:       190 seconds

	System Integrity Protection: enabled

	Crashed Thread:        0

	Exception Type:        EXC_BREAKPOINT (SIGTRAP)
	Exception Codes:       0x0000000000000002, 0x0000000000000000
	Exception Note:        EXC_CORPSE_NOTIFY

	Application Specific Information:
	dyld: launch, loading dependent libraries

	Dyld Error Message:
	  Symbol not found: __TMSi
	  Referenced from: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftos.dylib
	  Expected in: /Applications/Haste.app/Contents/MacOS/../Frameworks/libswiftCore.dylib
	 in /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftos.dylib

	Binary Images:
	       0x10c407000 -        0x10c75aff7 +libswiftCore.dylib (4.1.2 - 902.0.54) <F318B448-C59C-3FE4-A2F5-28807B333CDE> /Applications/Haste.app/Contents/Frameworks/libswiftCore.dylib
	       0x10ca0b000 -        0x10ca14fff +libswiftCoreData.dylib (4.1.2 - 902.0.54) <CDB72D6F-F272-3028-8033-99D7589452E1> /Applications/Haste.app/Contents/Frameworks/libswiftCoreData.dylib
	       0x10ca29000 -        0x10ca2cfff +libswiftCoreFoundation.dylib (4.1.2 - 902.0.54) <B4751639-D527-3851-B923-10FE0A7F7E10> /Applications/Haste.app/Contents/Frameworks/libswiftCoreFoundation.dylib
	       0x10ca39000 -        0x10ca4bfff +libswiftCoreGraphics.dylib (4.1.2 - 902.0.54) <A37BDDBC-C0A5-32A1-BF50-104280CD59F9> /Applications/Haste.app/Contents/Frameworks/libswiftCoreGraphics.dylib
	       0x10ca8c000 -        0x10ca93ff7 +libswiftDarwin.dylib (4.1.2 - 902.0.54) <F691AB87-664D-3032-8DFC-7B43F153430D> /Applications/Haste.app/Contents/Frameworks/libswiftDarwin.dylib
	       0x10caaa000 -        0x10cac4ff7 +libswiftDispatch.dylib (4.1.2 - 902.0.54) <983D3A77-6B82-34EF-A911-85FCD411A20D> /Applications/Haste.app/Contents/Frameworks/libswiftDispatch.dylib
	       0x10cafa000 -        0x10cc6eff7 +libswiftFoundation.dylib (4.1.2 - 902.0.54) <3E95BEE7-7BA5-3073-9EB8-FD8BD3FC5C59> /Applications/Haste.app/Contents/Frameworks/libswiftFoundation.dylib
	       0x10cdbc000 -        0x10cdbfff7 +libswiftIOKit.dylib (4.1.2 - 902.0.54) <DCCC358D-C25E-3D62-99F4-D30E103FD262> /Applications/Haste.app/Contents/Frameworks/libswiftIOKit.dylib
	       0x10cde2000 -        0x10cde8fff +libswiftObjectiveC.dylib (4.1.2 - 902.0.54) <A357C008-2D9C-3F5A-BC78-9A016E1CF3EF> /Applications/Haste.app/Contents/Frameworks/libswiftObjectiveC.dylib
	       0x10ce16000 -        0x10ce19fff +libswiftXPC.dylib (4.1.2 - 902.0.54) <7D80DFCA-CAC4-390C-908A-7E620BF8ED20> /Applications/Haste.app/Contents/Frameworks/libswiftXPC.dylib
	(Cont.)

</details>

And for the following part in the crash report:

	Dyld Error Message:
	  Symbol not found: __TMSi
	  Referenced from: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftos.dylib
	  Expected in: /Applications/Haste.app/Contents/MacOS/../Frameworks/libswiftCore.dylib
	 in /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftos.dylib

We wondered why the app tried to reference the libswiftos.dylib from under **"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/"** rather than the framework directory under the application's executable path. 

After some investigation, we found that the **Runtime Search Path** (for FavIcon-macOS target) of the FavIcon.xcodeproj is set to "$(TOOLCHAIN_DIR)/usr/lib/swift/macosx", that renders to the aforementioned path. (Presumably the app tried to load the .dylib from there rather than from within the app itself because the .dylib existed in there, but crashed as its version was incompatible when the version of the Xcode was old).

Setting the specified Runtime Search Path to empty seemed to have resolved the issue.
(Some other libraries seems to have it "@executable_path/../Frameworks", others have it empty, I am not sure which should be appropriate - We just had it empty and it seems to be working OK).

Changing a Runtime Search Path before building FavIcon library is tribal, however it would be hard to maintain as we manage the libraries for the project with Carthage.

Would you please consider about changing the Runtime Search Path for FavIcon-macOS target as appropriate? Please let me know what you think. Thanks!

**Comment by leonbreedt** [comment]
Thanks for the report, will investigate. I don't remember explicitly setting that search path, I wonder how it got in there. Also trying to figure out how to reference libxml2 in a way that works on many Xcode versions without vendoring it! Argh.

**Comment by leonbreedt** [comment]
Thanks for the report, I've released `3.0.5` which updates the macOS Runtime Search Path. Let me know if you have any issues! Cheers.

**Comment by muscledocking** [comment]
Awesome, thanks again for your response and the fantastic work!

**Comment by gk-plastics** [comment]
Awesome, thanks again for your response and the fantastic work!
