### ISSUE TITLE
Low-Res Icons being loaded for some Pages

### ISSUE THREAD

**Issue by winsmith** [leonbreedt/FavIcon#24]
Hi! Thanks for this fantastic library. 

I have an issue where I use the exact sample code from the readme, but get low-resolution images for some pages: 

<img width="234" alt="screenshot 2018-10-31 at 14 51 15" src="https://user-images.githubusercontent.com/954120/47794851-8f249a00-dd21-11e8-9071-679409952bf6.png">

A page where I've seen this is Facebook. Both `m.facebook.com` and `www.facebook.com` return icons that are not the highest resolution. The same seems to be happening with `www.youtube.com`.

Do you have any pointers what I might be doing wrong, or where I could look around to debug this? I'm happy to provide a PR once I find a solution to the issue :)

**Comment by leonbreedt** [comment]
Hello @winsmith,

It looks like Facebook just returns a 16x16 image for the types of icon we supported.

However, I found that it has a high-res image in `<meta property="og:image">`, so I added experimental support for this in `3.0.5`. 

Let me know if this helps.

Cheers.

**Comment by winsmith** [comment]
Hi @leonbreedt,

thanks a lot, for your help. Another issue I'm seeing is that, if I request an icon with e.g. width and height of 200, Youtube still loads a 16 by 16 image. This is because in `Detection.swift:48`, the code insists that there must be a `type` specified for the icon in HTML:

```swift
        case "icon":
            guard let type = link.attributes["type"] else { continue }
            guard type.lowercased() == "image/png" else { continue }
```

Is this strictly necessary? A lot of websites expose the icon but do not specify the type. Here's Youtube again: 

```html
<link rel="shortcut icon" href="https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico" type="image/x-icon" >
<link rel="icon" href="https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png" sizes="32x32" >
<link rel="icon" href="https://s.ytimg.com/yts/img/favicon_48-vflVjB_Qk.png" sizes="48x48" >
<link rel="icon" href="https://s.ytimg.com/yts/img/favicon_96-vflW9Ec0w.png" sizes="96x96" >
<link rel="icon" href="https://s.ytimg.com/yts/img/favicon_144-vfliLAfaB.png" sizes="144x144" >
```

The FavIcon library is missing all these sizes right now because they don't have a type specified. If I comment out lines 48 and 49 in `Detection.swift`, I get these as well, and I didn't get adverse effects. 

Maybe the check isn't needed or could be replaced by a check that ensures the file ends in `.png`?

**Comment by leonbreedt** [comment]
@winsmith seems a reasonable request, i will add to todo list. PR also welcome of course :)

**Comment by winsmith** [comment]
Awesome! PR sent :)
