### ISSUE TITLE
Release 3.1.0 not available on CocoaPods

### ISSUE THREAD

**Issue by robertveringa89** [leonbreedt/FavIcon#31]
Hi leonbreedt,

First of all, thanks for taking the time to update this repo to Swift 5.
However, I can't find the latest version (3.1.0) on CocoaPods. Could you push this version to the CocoaPods repo?

Best regards,

Robert

**Comment by leonbreedt** [comment]
@robertveringa89 thanks for the reminder, CocoaPods was down when I did the 3.1.0 release, and I forgot to try again later.

just published it, should be there in a couple of minutes.
